apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-http
  name: simple-http
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-http
