apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simple-http
  labels:
    app: simple-http
spec:
  selector:
    matchLabels:
      app: simple-http
  endpoints:
  - port: web
    path: /metrics
